### ISSUE TITLE
Uncaught PHP Exception ErrorException: "Warning: curl_multi_setopt() expects parameter 1 to be resource, integer given"

### ISSUE THREAD

**Issue by willbrid** [symfony/mercure-bundle#17]
**Symfony version(s) affected**: 4.3.6

**Description**  
Hi, Please i have a problem.
After installing mercure bundle who come with symfony/http-client, when i load a simple page, the toolbar didn't show again and i have this error below :

```
Nov 11 01:18:22 |CRITI| REQUES Uncaught PHP Exception ErrorException: "Warning: curl_multi_setopt() expects parameter 1 to be resource, integer given" at /var/www/html/project_sf4/vendor/symfony/http-client/CurlHttpClient.php line 302 exception="[object] (ErrorException(code: 0): Warning: curl_multi_setopt() expects parameter 1 to be resource, integer given at /var/www/html/project_sf4/vendor/symfony/http-client/CurlHttpClient.php:302)"
Nov 11 01:18:23 |ERROR| SERVER GET  (500) /_wdt/1d91a6
```

**How to reproduce**  
Just install mercure bundle
```
composer require mercure
```

**Comment by chalasr** [comment]
Hey, this is due to a bug on the symfony/http-client paxckage which has been fixed in https://github.com/symfony/symfony/pull/34287. The patch will be available in the next Symfony 4.3 release.

Until it is released, you can either disable the mercure-bundle profiler integration by setting `enable_profiler` to false in your `config/packages/mercure.yaml` config file, or require `symfony/http-client:4.3.x-dev` in your composer.json.

**Comment by willbrid** [comment]
Thank you i set enable_profiler to false and it work for me.

**Comment by chalasr** [comment]
Symfony 4.3.7 has been released, you can `composer update symfony/*` and re-enable the profiler integration!
